export default {
    login: "https://compassion-africa.org/api/user/login/",
    register: "https://compassion-africa.org/api/user/register/",
    dashboard_statistics: "https://compassion-africa.org/api/user/get_dashboard_statistics/",
    themes: "https://compassion-africa.org/api/user/themes/",
    add_goal: "https://compassion-africa.org/api/user/add_goal/",
    add_plan: "https://compassion-africa.org/api/user/add_plan/",
    get_goal: "https://compassion-africa.org/api/user/goal/",
    add_task: 'https://compassion-africa.org/api/user/add_task/',
    task_types: "https://compassion-africa.org/api/user/get_task_types",
    goals: "https://compassion-africa.org/api/user/goals/",
    goal: "https://compassion-africa.org/api/user/goal/",
    tasks: "https://compassion-africa.org/api/user/tasks/",
    task: "https://compassion-africa.org/api/user/task/",
    add_task_note: "https://compassion-africa.org/api/user/add_task_note/",
    task_notes: "https://compassion-africa.org/api/user/get_task_notes/",
    get_plans: "https://compassion-africa.org/api/user/plans/",
    active_plan: "https://compassion-africa.org/api/user/active_plan/",
    get_plan: "https://compassion-africa.org/api/user/get_plan/",
    plan_statistics: "https://compassion-africa.org/api/user/plan_statistics/",
    update_task_status: "https://compassion-africa.org/api/user/update_task_status/",
    goal_statistics: "https://compassion-africa.org/api/user/goal_statistics/"
}