export default {
    appName: "Youth Planner",
    emptyTasks: "You have no Tasks Created",
    startDate: "Start Date",
    endDate: "End Date",
    taskTitle: "Task Title",
    taskDescription: "Task Description",
    taskStartDate: "Task Start Date",
    taskEndDate: "Task End Date",
    addGoal: "Add Goal",
    titleErrorMessage: 'Please fill Title',
    descriptionErrorMessage: 'Please fill Description',
    startDateErrorMessage: "Please fill Start Date",
    endDateErrorMessage: "Please fill End Date",
    confirmationAlertTitle: "Confirmation",
    confirmationAlertSubmitMessage: "Are you sure you want to submit this item?",
    agreeLabel: "Yes",
    canceLabel: "Cancel",
    addTask: "Add Task",
    confirmExitAppMessage: "Are you sure you want to exit the App?",
    ListStories: "List Stories",
    addStory: "Add a Story",
    overdueGoals: "Overdue goals",
    dueTasks: "Due tasks",
    overdueTasks: "Overdue Tasks",
    recentActivities: "Recent Activities",
    notices: "Notices",
    goalLabel: "Goal",
    themeLabel: "Theme",
    taskTypeErrorMessage: "Please fill in task type",
    emailPasswordNotFound: "Please check your email id or password",
    enterEmail: "Enter Email",
    enterPassword: "Enter Password",
    login: "Login",
    taskLabel: "Task",
    student: "Student"
}